# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PlantFactory' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod "BSImagePicker", "~> 3.1"

  # Pods for upload

  target 'PlantFactoryTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PlantFactoryUITests' do
    # Pods for testing
  end

end
